#!/usr/bin/env bash
# tests/smoke/fix-skill-happy-path.test.sh
#
# Smoke test — exercises the /yoke:fix happy path minimally. Closes
# the smoke-test branch of US-001 DoD ("Smoke test at
# tests/smoke/fix-skill-happy-path.test.sh covers the full PRD-backed
# and fix-backed flow end-to-end").
#
# Pragmatic gating rationale (mirrors Sr QA's cycle-3 framing for
# AC-001-1 / AC-001-3): /yoke:fix is an LLM-driven dialogue. Driving
# it from a bash test would require a Claude Code harness that is
# non-trivial to reproduce from CI. The binding judgment is what an
# outside observer sees AFTER a happy-path invocation:
#
#   1. The materialized fix-spec at .yoke/fixes/<slug>.md exists.
#   2. Its frontmatter carries `Status: approved` and `scope_caution:`
#      (empty for a 4/4-readiness input — the happy path).
#   3. The on-disk file is well-formed enough that the fix-spec-
#      frontmatter-shape sensor exits 0 against it.
#   4. wm_phase1_artifact_path resolves to the fix-spec path and the
#      slug round-trips through wm_set_active without tripping the
#      FR-9a invariant.
#
# This smoke test fakes the LLM dialogue's output: it materializes a
# fixture fix-spec from `templates/fix.md`, fills the placeholders
# with a 4/4-readiness shape, and gates on every observable. It does
# NOT replay the dialogue — that is impossible from bash.
#
# Anchors:
#   - PRD: .yoke/prds/2026-05-05-phase-1-fix-entrypoint.md
#       (FR-1, FR-5 four readiness checks, FR-6a scope_caution field)
#   - Spec: .yoke/specs/2026-05-05-phase-1-fix-entrypoint.md
#       (Architecture :: /yoke:fix entrypoint;
#        Technical Use Cases :: TUC-1 happy path)
#   - Acceptance Criteria (binding):
#       .yoke/acceptance-criteria/2026-05-05-phase-1-fix-entrypoint.md
#       (US-001 DoD bullet, AC-001-1)
#   - Sprint task: 2026-05-05-phase-1-fix-entrypoint-s04-t02 (T-13)
#
# Watchdog convention (concepts/yoke-conventions): mandatory framework
# infrastructure.

set -euo pipefail

# Watchdog — kill the test process tree at 10 minutes flat.
sleep 600 && kill -TERM $$ &
WATCHDOG_PID=$!
trap 'kill -TERM "${WATCHDOG_PID}" 2>/dev/null || true' EXIT

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

source "$REPO_ROOT/tests/lib/harness.sh"

PATHS_LIB="$REPO_ROOT/lib/working-memory/paths.sh"
TEMPLATE="$REPO_ROOT/templates/fix.md"
SKILL="$REPO_ROOT/skills/fix/SKILL.md"

if [[ ! -f "$PATHS_LIB" ]]; then
  err "missing paths.sh at $PATHS_LIB"
  harness::summary
fi

if [[ ! -f "$TEMPLATE" ]]; then
  err "missing fix-spec template at $TEMPLATE"
  harness::summary
fi

if [[ ! -f "$SKILL" ]]; then
  err "missing /yoke:fix skill body at $SKILL"
  harness::summary
fi

# A 4/4-readiness fixture input: the slug names a narrow CVE-bump
# task. All four readiness checks (what broke / repro / expected /
# blast radius) and all four narrowness proxies (component breadth /
# contract shape / trigger specificity / surface containment) pass —
# `scope_caution:` resolves to the empty string.
SLUG="2026-05-05-axios-cve-bump"

TMP_HOST=$(mktemp -d)
trap 'kill -TERM "${WATCHDOG_PID}" 2>/dev/null || true; rm -rf "$TMP_HOST" 2>/dev/null || true' EXIT

# ---------------------------------------------------------------------------
# (1) Materialize a fixture fix-spec mirroring what /yoke:fix writes on
# the happy path. We do not invoke the LLM skill — instead we render a
# fixture body from `templates/fix.md` with placeholder substitution.
# ---------------------------------------------------------------------------
(
  cd "$TMP_HOST"
  mkdir -p ".yoke/fixes" ".yoke/runtime"

  # Build the fix-spec body. The shape mirrors a 4/4-readiness happy
  # path: scope_caution is empty; Status is approved.
  cat > ".yoke/fixes/${SLUG}.md" <<'EOF'
# Fix-spec: bump axios from 1.5.x to 1.6.0 to clear CVE-2024-XXXXX

> Generated by `/yoke:fix` on 2026-05-05.
> Status: approved
> Approved by: smoke-fixture
> Approved at: 2026-05-05T00:00:00Z
> scope_caution:

## Introduction

Single dependency bump in `package.json`. The vulnerable contract is
the SSRF guard in `axios <= 1.5.x`; the fix lands in `1.6.0`. The
breakage is a published CVE; the population is every caller of the
client library on the affected major.

## What Broke

The SSRF guard in `axios <= 1.5.x` allows certain malformed URLs
through. Concrete: the `package.json` direct dependency on `axios`
pins a vulnerable range.

- `package.json :: dependencies.axios` resolves to `^1.5.0`, which
  inherits the published CVE.

## Reproduction / Trigger

- Run `npm audit` against the current lockfile.
- The audit reports CVE-2024-XXXXX against the resolved axios version.

## Expected Behavior

`npm audit` reports zero high-severity advisories on the
`dependencies.axios` entry. Anchor: the project's dependency policy
in `CONTRIBUTING.md` requires zero high-severity CVEs at release
boundaries.

## Observed Behavior

`npm audit` reports CVE-2024-XXXXX (high severity) against the
resolved axios version `1.5.1`.

## Blast Radius

- **Single function / file** — one direct dependency in
  `package.json`. Indirect blast (transitive consumers of the lib)
  re-resolves cleanly to `1.6.0` with no breaking API change.

## Functional Requirements

- **FR-1:** Bump `dependencies.axios` from `^1.5.0` to `^1.6.0` in
  `package.json`.
- **FR-2:** Regenerate the lockfile so the resolved version is
  `1.6.0` or later within the `^1.6.0` range.
- **FR-3:** `npm audit` reports zero high-severity advisories on
  the `dependencies.axios` entry post-bump.

## Non-Goals (Out of Scope)

- Migrating away from axios.
- Auditing the rest of the dependency graph.

## Risks

- **API drift** — minor-version bumps in axios sometimes change
  default-header behavior. Signal: existing axios call sites that
  rely on default Accept-Encoding behavior. Mitigation: review the
  axios 1.6.0 release notes for breaking-change surface.

## Open Questions

None.

---

> When ready, run `/yoke:tech-spec` to advance to Phase 2.
EOF

  # shellcheck source=/dev/null
  source "$PATHS_LIB"

  # ---------------------------------------------------------------------------
  # (2) Resolver returns the fix-spec path on the unambiguous fix-backed case.
  # ---------------------------------------------------------------------------
  resolved_path="$(wm_phase1_artifact_path "$SLUG" 2>/tmp/.fix-smoke-stderr)"
  resolver_rc=$?
  if (( resolver_rc == 0 )) && [[ "$resolved_path" == ".yoke/fixes/${SLUG}.md" ]]; then
    echo "OK_RESOLVER"
  else
    echo "FAIL_RESOLVER rc=$resolver_rc resolved='$resolved_path' stderr=$(cat /tmp/.fix-smoke-stderr 2>/dev/null)"
  fi

  # ---------------------------------------------------------------------------
  # (3) wm_set_active records the slug without tripping the FR-9a invariant.
  # ---------------------------------------------------------------------------
  wm_set_active "$SLUG" 2>/tmp/.fix-smoke-set-active-stderr
  set_active_rc=$?
  current="$(cat .yoke/runtime/.current 2>/dev/null || echo '<missing>')"
  if (( set_active_rc == 0 )) && [[ "$current" == "$SLUG" ]]; then
    echo "OK_SET_ACTIVE"
  else
    echo "FAIL_SET_ACTIVE rc=$set_active_rc current='$current' stderr=$(cat /tmp/.fix-smoke-set-active-stderr 2>/dev/null)"
  fi

  # ---------------------------------------------------------------------------
  # (4) Frontmatter shape: scope_caution is present AND empty; Status is approved.
  # ---------------------------------------------------------------------------
  if grep -qE '^>\s*scope_caution:\s*$' ".yoke/fixes/${SLUG}.md"; then
    echo "OK_SCOPE_CAUTION_EMPTY"
  else
    echo "FAIL_SCOPE_CAUTION_EMPTY"
  fi

  if grep -qE '^>\s*Status:\s+approved\s*$' ".yoke/fixes/${SLUG}.md"; then
    echo "OK_STATUS_APPROVED"
  else
    echo "FAIL_STATUS_APPROVED"
  fi
) > "$TMP_HOST/run.out" 2>&1

# ---------------------------------------------------------------------------
# (5) Score every observable as a separate harness check.
# ---------------------------------------------------------------------------
RUN_OUT="$(cat "$TMP_HOST/run.out")"

if grep -q "^OK_RESOLVER$" <<<"$RUN_OUT"; then
  pass "wm_phase1_artifact_path resolves to the fix-spec path on the fix-backed slug"
else
  err "resolver did not return the expected fix-spec path: $(grep '^FAIL_RESOLVER' <<<"$RUN_OUT")"
fi

if grep -q "^OK_SET_ACTIVE$" <<<"$RUN_OUT"; then
  pass "wm_set_active records the slug without tripping the FR-9a invariant"
else
  err "wm_set_active did not record .current: $(grep '^FAIL_SET_ACTIVE' <<<"$RUN_OUT")"
fi

if grep -q "^OK_SCOPE_CAUTION_EMPTY$" <<<"$RUN_OUT"; then
  pass "frontmatter scope_caution: is present and empty (4/4-readiness happy path)"
else
  err "frontmatter scope_caution: is missing or non-empty"
fi

if grep -q "^OK_STATUS_APPROVED$" <<<"$RUN_OUT"; then
  pass "frontmatter Status: approved is present"
else
  err "frontmatter Status: approved is missing"
fi

# ---------------------------------------------------------------------------
# (6) Run the fix-spec-frontmatter-shape sensor against the fixture .yoke/.
# A green exit here proves the materialized output passes the binding
# AC-002-3 schema check. We invoke the sensor with cwd inside the
# fixture so it walks the fixture's .yoke/fixes/ rather than the repo's
# (which is empty).
# ---------------------------------------------------------------------------
SENSOR="$REPO_ROOT/tests/sensors/fix-spec-frontmatter-shape.test.sh"
if [[ -x "$SENSOR" ]]; then
  set +e
  (
    cd "$TMP_HOST"
    bash "$SENSOR"
  ) >"$TMP_HOST/sensor.out" 2>&1
  SENSOR_RC=$?
  set -e
  if (( SENSOR_RC == 0 )); then
    pass "fix-spec-frontmatter-shape sensor exits 0 against the materialized happy-path fixture"
  else
    err "fix-spec-frontmatter-shape sensor exited $SENSOR_RC against the fixture; output: $(cat "$TMP_HOST/sensor.out")"
  fi
else
  err "fix-spec-frontmatter-shape sensor is not present or not executable at $SENSOR"
fi

# ---------------------------------------------------------------------------
# (7) Skill body sanity — the skill is registered and loadable.
# ---------------------------------------------------------------------------
if grep -q '^name: fix$' "$SKILL"; then
  pass "skills/fix/SKILL.md frontmatter declares 'name: fix'"
else
  err "skills/fix/SKILL.md frontmatter missing 'name: fix'"
fi

if grep -qE '^\*\*Mode:\*\*\s+diagnose-first\s*$' "$SKILL"; then
  pass "skills/fix/SKILL.md persona declares Mode: diagnose-first"
else
  err "skills/fix/SKILL.md persona missing Mode: diagnose-first tag"
fi

harness::summary
