#!/usr/bin/env bash
# tests/lib/fix-spec-frontmatter-shape-sensor.test.sh
#
# Happy-path + negative coverage for the fix-spec-frontmatter-shape CI
# sensor added by the /yoke:fix Phase-1-entrypoint PRD (Sprint 03,
# Task t05):
#
#   tests/sensors/fix-spec-frontmatter-shape.test.sh
#     Walks every .yoke/fixes/<slug>.md (when present) and asserts each
#     carries the mandatory `scope_caution:` key in its frontmatter
#     with one of the documented values:
#       <empty> | component-breadth | contract-shape |
#       trigger-specificity | surface-containment
#
# Anchors:
#   - PRD: .yoke/prds/2026-05-05-phase-1-fix-entrypoint.md (FR-6a)
#   - Acceptance Criteria (binding):
#       .yoke/acceptance-criteria/2026-05-05-phase-1-fix-entrypoint.md
#       (AC-002-3)
#   - Sprint task: 2026-05-05-phase-1-fix-entrypoint-s03-t05
#
# The test exercises the real sensor against tmpdir clones of the
# repo so the host project's `.yoke/fixes/` directory (which is empty
# at the time of writing) is never mutated.
#
# Watchdog convention (concepts/yoke-conventions): smoke / runtime
# tests must guard against ralph-loop iterations or LLM-driven steps
# without hard bounds.

set -euo pipefail

sleep 600 && kill -TERM $$ &
WATCHDOG_PID=$!
trap 'kill "${WATCHDOG_PID}" 2>/dev/null || true' EXIT

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SENSOR="${REPO_ROOT}/tests/sensors/fix-spec-frontmatter-shape.test.sh"

FAIL=0
PASS_COUNT=0

fail() { echo "FAIL: $*" >&2; FAIL=1; }
pass() { echo "PASS: $*"; PASS_COUNT=$((PASS_COUNT + 1)); }

[ -x "$SENSOR" ] || chmod +x "$SENSOR"

mk_fixture_dir() {
  local d
  d="$(mktemp -d)"
  mkdir -p "${d}/.yoke/fixes" "${d}/tests/sensors"
  cp "$SENSOR" "${d}/tests/sensors/fix-spec-frontmatter-shape.test.sh"
  chmod +x "${d}/tests/sensors/fix-spec-frontmatter-shape.test.sh"
  echo "$d"
}

# --- (a) vacuous: no .yoke/fixes/ directory ------------------------------
fixdir="$(mktemp -d)"
mkdir -p "${fixdir}/tests/sensors"
cp "$SENSOR" "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh"
chmod +x "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh"
set +e
out="$(bash "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh" 2>&1)"
ec=$?
set -e
if [ "$ec" -eq 0 ] && echo "$out" | grep -q 'does not exist'; then
  pass "(a) vacuous: missing .yoke/fixes/ directory passes silently"
else
  fail "(a) vacuous: expected exit 0 + 'does not exist' message, got ec=${ec}"
  printf '%s\n' "$out" | head -10 >&2
fi
rm -rf "$fixdir"

# --- (b) vacuous: empty .yoke/fixes/ directory ---------------------------
fixdir="$(mk_fixture_dir)"
set +e
out="$(bash "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh" 2>&1)"
ec=$?
set -e
if [ "$ec" -eq 0 ] && echo "$out" | grep -q 'is empty'; then
  pass "(b) vacuous: empty .yoke/fixes/ directory passes silently"
else
  fail "(b) vacuous: expected exit 0 + 'is empty' message, got ec=${ec}"
  printf '%s\n' "$out" | head -10 >&2
fi
rm -rf "$fixdir"

# --- (c) positive: empty scope_caution (4/4 narrowness proxies passed) ---
fixdir="$(mk_fixture_dir)"
cat > "${fixdir}/.yoke/fixes/2026-05-05-foo.md" <<'EOF'
# Fix-spec: foo

> Generated by `/yoke:fix` on 2026-05-05.
> Status: approved
> Approved by: tester
> Approved at: 2026-05-05T00:00:00Z
> scope_caution:

## Introduction

Body.
EOF
set +e
out="$(bash "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh" 2>&1)"
ec=$?
set -e
if [ "$ec" -eq 0 ] && echo "$out" | grep -q 'scope_caution is empty'; then
  pass "(c) positive: empty scope_caution accepted (4/4 narrowness proxies passed)"
else
  fail "(c) positive: expected exit 0 + 'scope_caution is empty' message, got ec=${ec}"
  printf '%s\n' "$out" | head -10 >&2
fi
rm -rf "$fixdir"

# --- (d) positive: documented value (component-breadth) ------------------
fixdir="$(mk_fixture_dir)"
cat > "${fixdir}/.yoke/fixes/2026-05-05-bar.md" <<'EOF'
# Fix-spec: bar

> Generated by `/yoke:fix` on 2026-05-05.
> Status: approved
> scope_caution: component-breadth

## Introduction

Body.
EOF
set +e
out="$(bash "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh" 2>&1)"
ec=$?
set -e
if [ "$ec" -eq 0 ] && echo "$out" | grep -q "scope_caution = 'component-breadth'"; then
  pass "(d) positive: documented value 'component-breadth' accepted"
else
  fail "(d) positive: expected exit 0 + documented-value match, got ec=${ec}"
  printf '%s\n' "$out" | head -10 >&2
fi
rm -rf "$fixdir"

# --- (e) negative: missing scope_caution key -----------------------------
fixdir="$(mk_fixture_dir)"
cat > "${fixdir}/.yoke/fixes/2026-05-05-baz.md" <<'EOF'
# Fix-spec: baz

> Generated by `/yoke:fix` on 2026-05-05.
> Status: approved

## Introduction

Body — note no `scope_caution:` line above.
EOF
set +e
out="$(bash "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh" 2>&1)"
ec=$?
set -e
if [ "$ec" -ne 0 ] && echo "$out" | grep -q "missing mandatory 'scope_caution:'"; then
  pass "(e) negative: missing scope_caution key trips the sensor"
else
  fail "(e) negative: expected non-zero exit + missing-key diagnostic, got ec=${ec}"
  printf '%s\n' "$out" | head -10 >&2
fi
rm -rf "$fixdir"

# --- (f) negative: undocumented value -----------------------------------
fixdir="$(mk_fixture_dir)"
cat > "${fixdir}/.yoke/fixes/2026-05-05-qux.md" <<'EOF'
# Fix-spec: qux

> Generated by `/yoke:fix` on 2026-05-05.
> Status: approved
> scope_caution: feature-creep

## Introduction

Body.
EOF
set +e
out="$(bash "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh" 2>&1)"
ec=$?
set -e
if [ "$ec" -ne 0 ] && echo "$out" | grep -q 'feature-creep'; then
  pass "(f) negative: undocumented value 'feature-creep' trips the sensor with observed value in output"
else
  fail "(f) negative: expected non-zero exit + undocumented-value diagnostic, got ec=${ec}"
  printf '%s\n' "$out" | head -10 >&2
fi
rm -rf "$fixdir"

# --- (g) positive: every documented value accepted -----------------------
fixdir="$(mk_fixture_dir)"
for v in component-breadth contract-shape trigger-specificity surface-containment; do
  cat > "${fixdir}/.yoke/fixes/2026-05-05-${v}.md" <<EOF
# Fix-spec: ${v}

> Generated by \`/yoke:fix\` on 2026-05-05.
> Status: approved
> scope_caution: ${v}

## Introduction

Body.
EOF
done
set +e
out="$(bash "${fixdir}/tests/sensors/fix-spec-frontmatter-shape.test.sh" 2>&1)"
ec=$?
set -e
if [ "$ec" -eq 0 ]; then
  pass "(g) positive: all 4 documented non-empty values accepted in one walk"
else
  fail "(g) positive: expected exit 0 with 4 fix-specs, got ec=${ec}"
  printf '%s\n' "$out" | head -20 >&2
fi
rm -rf "$fixdir"

echo
if [ "$FAIL" -eq 0 ]; then
  echo "--- fix-spec-frontmatter-shape-sensor: ALL PASS (${PASS_COUNT}/7) ---"
  exit 0
else
  echo "--- fix-spec-frontmatter-shape-sensor: FAILURES ABOVE ---" >&2
  exit 1
fi
