#!/bin/bash
# tests/sensors/template-metadata-fidelity.test.sh
#
# Self-test for lib/sensors/template-metadata-fidelity.sh. Exercises
# three subcases:
#   - positive:        real templates/ tree post-fix → exit 0, empty stderr
#   - negative:        drifted fixture in tmpdir → exit non-zero, expected
#                      violation classes on stderr
#   - reverse-fixture: synthetic producer-owned template added to a
#                      tmpdir-extended allowlist → exit 0
#
# All probes run inside ephemeral $tmp trees to avoid polluting the
# working tree. The sensor is invoked with the fixture as CWD so its
# allowlist's relative paths (templates/sprint.md,
# skills/generate-sprints/SKILL.md) resolve against the fixture.
#
# Source: .yoke/acceptance-criteria/2026-05-05-template-attribution-drift.md
# AC-003-2 / AC-003-3 / AC-003-6.

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SENSOR="${PLUGIN_ROOT}/lib/sensors/template-metadata-fidelity.sh"

fail=0
pass() { echo "PASS: $1"; }
err()  { echo "FAIL: $1" >&2; fail=$((fail + 1)); }

echo "--- template-metadata-fidelity sensor self-test ---"

# 0. Sensor file exists and is executable.
[[ -f "$SENSOR" ]] || { err "sensor missing at ${SENSOR}"; exit 1; }
[[ -x "$SENSOR" ]] && pass "sensor is executable" || err "sensor not executable"

# ---------------------------------------------------------------------
# Positive subcase — real templates/ tree post-fix.
# ---------------------------------------------------------------------
positive_stderr="$(mktemp)"
trap 'rm -f "$positive_stderr"' EXIT

if (cd "$PLUGIN_ROOT" && bash "$SENSOR") 2>"$positive_stderr"; then
  pass "positive: real templates/ tree → exit 0"
else
  err "positive: real templates/ tree should exit 0 but did not"
  cat "$positive_stderr" >&2 || true
fi

if [[ -s "$positive_stderr" ]]; then
  err "positive: stderr should be empty on real templates/ tree"
  cat "$positive_stderr" >&2 || true
else
  pass "positive: stderr is empty"
fi

# ---------------------------------------------------------------------
# Negative subcase — drifted fixture in tmpdir.
# Fixture mirrors the pre-fix templates/sprint.md attribution drift
# documented in .yoke/fixes/2026-05-05-template-attribution-drift.md
# (opening blockquote citing /yoke:tech-spec stage 3 and Trigger 2).
# Expected: exit non-zero with producer-mismatch + trigger-mismatch +
# legacy-string-leaked violations on stderr.
# ---------------------------------------------------------------------
neg_tmp="$(mktemp -d)"
trap 'rm -rf "$neg_tmp" "$positive_stderr"' EXIT

mkdir -p "${neg_tmp}/templates" "${neg_tmp}/skills/generate-sprints" "${neg_tmp}/lib/sensors"
cp "$SENSOR" "${neg_tmp}/lib/sensors/"

# Construct the drifted fixture. The opening blockquote and the closing
# trailer cite the pre-cutover producer/trigger; the legacy-flow
# carve-out paragraph in the middle is preserved (the sensor must NOT
# flag the carve-out, only the surrounding blockquotes).
# Build the legacy strings via concatenation so this fixture file does
# not itself trip the sensor when invoked from elsewhere.
LEGACY_PRODUCER='/yoke:tech'"-spec"' (stage 3)'
LEGACY_TRIGGER='Trigger 2'" approves the parent spec"

cat > "${neg_tmp}/templates/sprint.md" <<EOF
# Sprint <NN> of <MM>: <one-line sprint name>

> Generated by ${LEGACY_PRODUCER} from \`.yoke/specs/<slug>.md\`.
> Status flips to \`approved\` when ${LEGACY_TRIGGER}.

## Sprint objective

stub objective

## Sprint DoD

- stub bullet

## Tasks

### Task <slug>-s<NN>-t01

stub task

> **legacy-flow carve-out.** Pre-cutover sprint files generated by
> the legacy producer pre-cutover are exempt from the (Realizes: ...)
> US-trace clause.

## Functional acceptance criteria

- stub-id

## Sensors

- stub-sensor

---

> Generated by ${LEGACY_PRODUCER} from \`.yoke/specs/<slug>.md\`.
> Status flips to \`approved\` when ${LEGACY_TRIGGER}.
EOF

# Real producer skill (just needs to exist for the boundary check).
cat > "${neg_tmp}/skills/generate-sprints/SKILL.md" <<EOF
# /yoke:generate-sprints
stub
EOF

neg_stderr="$(mktemp)"
trap 'rm -rf "$neg_tmp" "$positive_stderr" "$neg_stderr"' EXIT

if (cd "$neg_tmp" && bash "lib/sensors/template-metadata-fidelity.sh") 2>"$neg_stderr"; then
  err "negative: drifted fixture should make sensor exit non-zero"
else
  pass "negative: drifted fixture → non-zero exit"
fi

# Verify the four required keys (id / location / correction_instruction
# / reference) appear in the stderr output.
for key in 'id: template-metadata-fidelity:' 'location:' 'correction_instruction:' 'reference: "\[\[yoke-pattern-sensors\]\]"'; do
  if grep -qE "$key" "$neg_stderr"; then
    pass "negative: stderr carries '$(echo "$key" | head -c 30)'"
  else
    err "negative: stderr missing '$(echo "$key" | head -c 30)'"
    cat "$neg_stderr" >&2 || true
  fi
done

# Verify each violation class fires at least once.
for klass in 'producer-mismatch' 'trigger-mismatch' 'legacy-string-leaked'; do
  if grep -qF ":${klass}" "$neg_stderr"; then
    pass "negative: emits ${klass}"
  else
    err "negative: did not emit ${klass}"
    cat "$neg_stderr" >&2 || true
  fi
done

# Boundary checks (template-missing, producer-skill-missing) — separate
# tmpdir, allowlist points at non-existent files.
boundary_tmp="$(mktemp -d)"
trap 'rm -rf "$neg_tmp" "$positive_stderr" "$neg_stderr" "$boundary_tmp"' EXIT
mkdir -p "${boundary_tmp}/lib/sensors"

# Use the real sensor with a fixture that has neither templates/sprint.md
# nor skills/generate-sprints/SKILL.md.
cp "$SENSOR" "${boundary_tmp}/lib/sensors/"
boundary_stderr="$(mktemp)"
trap 'rm -rf "$neg_tmp" "$positive_stderr" "$neg_stderr" "$boundary_tmp" "$boundary_stderr"' EXIT
if (cd "$boundary_tmp" && bash "lib/sensors/template-metadata-fidelity.sh") 2>"$boundary_stderr"; then
  err "boundary: empty fixture should make sensor exit non-zero"
else
  pass "boundary: empty fixture → non-zero exit"
fi
if grep -qF ':template-missing' "$boundary_stderr"; then
  pass "boundary: emits template-missing"
else
  err "boundary: did not emit template-missing"
  cat "$boundary_stderr" >&2 || true
fi

# producer-skill-missing — template exists but skill does not.
mkdir -p "${boundary_tmp}/templates"
cp "${neg_tmp}/templates/sprint.md" "${boundary_tmp}/templates/sprint.md"
boundary2_stderr="$(mktemp)"
trap 'rm -rf "$neg_tmp" "$positive_stderr" "$neg_stderr" "$boundary_tmp" "$boundary_stderr" "$boundary2_stderr"' EXIT
if (cd "$boundary_tmp" && bash "lib/sensors/template-metadata-fidelity.sh") 2>"$boundary2_stderr"; then
  err "boundary: missing skill should make sensor exit non-zero"
else
  pass "boundary: missing producer skill → non-zero exit"
fi
if grep -qF ':producer-skill-missing' "$boundary2_stderr"; then
  pass "boundary: emits producer-skill-missing"
else
  err "boundary: did not emit producer-skill-missing"
  cat "$boundary2_stderr" >&2 || true
fi

# ---------------------------------------------------------------------
# Reverse-fixture subcase — synthetic producer-owned template added to
# an extended allowlist, expect exit 0. Verifies that the only edit
# needed to onboard a future producer-owned template is an allowlist
# entry.
# ---------------------------------------------------------------------
rev_tmp="$(mktemp -d)"
trap 'rm -rf "$neg_tmp" "$positive_stderr" "$neg_stderr" "$boundary_tmp" "$boundary_stderr" "$boundary2_stderr" "$rev_tmp"' EXIT

mkdir -p "${rev_tmp}/templates" \
  "${rev_tmp}/skills/generate-sprints" \
  "${rev_tmp}/skills/__test_producer" \
  "${rev_tmp}/lib/sensors"

# Real templates/sprint.md (post-fix) and real skill.
cp "${PLUGIN_ROOT}/templates/sprint.md" "${rev_tmp}/templates/sprint.md"
cp "${PLUGIN_ROOT}/skills/generate-sprints/SKILL.md" "${rev_tmp}/skills/generate-sprints/SKILL.md"

# Synthetic producer-owned template.
cat > "${rev_tmp}/templates/__test_producer_owned.md" <<'EOF'
# Synthetic producer-owned template

> Generated by `/yoke:__test-producer` (Phase X.Y) from a stub source.
> Status flips when Trigger __test ratifies the synthetic plan.

## Body

stub

---

> Generated by `/yoke:__test-producer` (Phase X.Y) from a stub source.
> Status flips when Trigger __test ratifies the synthetic plan.
EOF

# Synthetic producer skill.
cat > "${rev_tmp}/skills/__test_producer/SKILL.md" <<'EOF'
# /yoke:__test-producer
stub
EOF

# Build a sensor with an extended allowlist by Python-patching the
# TEMPLATES array. This verifies the onboarding cost is bounded to the
# allowlist edit.
python3 - "$SENSOR" "${rev_tmp}/lib/sensors/template-metadata-fidelity.sh" <<'PY'
import sys
src, dst = sys.argv[1], sys.argv[2]
with open(src, encoding="utf-8") as fh:
    body = fh.read()
extension = '  "templates/__test_producer_owned.md|skills/__test_producer/SKILL.md|Trigger __test|/yoke:__test-producer"\n'
needle = '  "templates/sprint.md|skills/generate-sprints/SKILL.md|Trigger 2.5|/yoke:generate-sprints"\n'
if needle not in body:
    raise SystemExit(f"reverse-fixture: needle not found in {src}")
body = body.replace(needle, extension + needle, 1)
with open(dst, "w", encoding="utf-8") as fh:
    fh.write(body)
PY
chmod +x "${rev_tmp}/lib/sensors/template-metadata-fidelity.sh"

rev_stderr="$(mktemp)"
trap 'rm -rf "$neg_tmp" "$positive_stderr" "$neg_stderr" "$boundary_tmp" "$boundary_stderr" "$boundary2_stderr" "$rev_tmp" "$rev_stderr"' EXIT

if (cd "$rev_tmp" && bash "lib/sensors/template-metadata-fidelity.sh") 2>"$rev_stderr"; then
  pass "reverse-fixture: extended allowlist with synthetic template → exit 0"
else
  err "reverse-fixture: extended allowlist should exit 0"
  cat "$rev_stderr" >&2 || true
fi

if [[ -s "$rev_stderr" ]]; then
  err "reverse-fixture: stderr should be empty"
  cat "$rev_stderr" >&2 || true
else
  pass "reverse-fixture: stderr is empty"
fi

# ---------------------------------------------------------------------
# Final tally.
# ---------------------------------------------------------------------
if (( fail > 0 )); then
  echo "FAIL: ${fail} subcase(s) failed" >&2
  exit 1
fi

echo "all subcases passed"
exit 0
